// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuum/plugin/v1/common.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminFormControl int32

const (
	AdminFormControl_ADMIN_FORM_CONTROL_UNSPECIFIED AdminFormControl = 0
	AdminFormControl_ADMIN_FORM_CONTROL_TEXT        AdminFormControl = 1
	AdminFormControl_ADMIN_FORM_CONTROL_TEXTAREA    AdminFormControl = 2
	AdminFormControl_ADMIN_FORM_CONTROL_PASSWORD    AdminFormControl = 3
	AdminFormControl_ADMIN_FORM_CONTROL_NUMBER      AdminFormControl = 4
	AdminFormControl_ADMIN_FORM_CONTROL_SWITCH      AdminFormControl = 5
	AdminFormControl_ADMIN_FORM_CONTROL_SELECT      AdminFormControl = 6
)

// Enum value maps for AdminFormControl.
var (
	AdminFormControl_name = map[int32]string{
		0: "ADMIN_FORM_CONTROL_UNSPECIFIED",
		1: "ADMIN_FORM_CONTROL_TEXT",
		2: "ADMIN_FORM_CONTROL_TEXTAREA",
		3: "ADMIN_FORM_CONTROL_PASSWORD",
		4: "ADMIN_FORM_CONTROL_NUMBER",
		5: "ADMIN_FORM_CONTROL_SWITCH",
		6: "ADMIN_FORM_CONTROL_SELECT",
	}
	AdminFormControl_value = map[string]int32{
		"ADMIN_FORM_CONTROL_UNSPECIFIED": 0,
		"ADMIN_FORM_CONTROL_TEXT":        1,
		"ADMIN_FORM_CONTROL_TEXTAREA":    2,
		"ADMIN_FORM_CONTROL_PASSWORD":    3,
		"ADMIN_FORM_CONTROL_NUMBER":      4,
		"ADMIN_FORM_CONTROL_SWITCH":      5,
		"ADMIN_FORM_CONTROL_SELECT":      6,
	}
)

func (x AdminFormControl) Enum() *AdminFormControl {
	p := new(AdminFormControl)
	*p = x
	return p
}

func (x AdminFormControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminFormControl) Descriptor() protoreflect.EnumDescriptor {
	return file_continuum_plugin_v1_common_proto_enumTypes[0].Descriptor()
}

func (AdminFormControl) Type() protoreflect.EnumType {
	return &file_continuum_plugin_v1_common_proto_enumTypes[0]
}

func (x AdminFormControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminFormControl.Descriptor instead.
func (AdminFormControl) EnumDescriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

type SupportedPlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedPlatform) Reset() {
	*x = SupportedPlatform{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedPlatform) ProtoMessage() {}

func (x *SupportedPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedPlatform.ProtoReflect.Descriptor instead.
func (*SupportedPlatform) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedPlatform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SupportedPlatform) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	JsonSchema    string                 `protobuf:"bytes,4,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	AdminForm     *AdminFormDescriptor   `protobuf:"bytes,6,opt,name=admin_form,json=adminForm,proto3" json:"admin_form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSchema) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSchema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConfigSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *ConfigSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigSchema) GetAdminForm() *AdminFormDescriptor {
	if x != nil {
		return x.AdminForm
	}
	return nil
}

type AdminFormOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormOption) Reset() {
	*x = AdminFormOption{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormOption) ProtoMessage() {}

func (x *AdminFormOption) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormOption.ProtoReflect.Descriptor instead.
func (*AdminFormOption) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AdminFormOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AdminFormOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminFormOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AdminFormField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Control       AdminFormControl       `protobuf:"varint,4,opt,name=control,proto3,enum=continuum.plugin.v1.AdminFormControl" json:"control,omitempty"`
	Placeholder   string                 `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Secret        bool                   `protobuf:"varint,7,opt,name=secret,proto3" json:"secret,omitempty"`
	Multiline     bool                   `protobuf:"varint,8,opt,name=multiline,proto3" json:"multiline,omitempty"`
	DefaultValue  *structpb.Value        `protobuf:"bytes,9,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options       []*AdminFormOption     `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	Rows          int32                  `protobuf:"varint,11,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormField) Reset() {
	*x = AdminFormField{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormField) ProtoMessage() {}

func (x *AdminFormField) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormField.ProtoReflect.Descriptor instead.
func (*AdminFormField) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *AdminFormField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminFormField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminFormField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminFormField) GetControl() AdminFormControl {
	if x != nil {
		return x.Control
	}
	return AdminFormControl_ADMIN_FORM_CONTROL_UNSPECIFIED
}

func (x *AdminFormField) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *AdminFormField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AdminFormField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *AdminFormField) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

func (x *AdminFormField) GetDefaultValue() *structpb.Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *AdminFormField) GetOptions() []*AdminFormOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AdminFormField) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type AdminFormDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*AdminFormField      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	SubmitLabel   string                 `protobuf:"bytes,2,opt,name=submit_label,json=submitLabel,proto3" json:"submit_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormDescriptor) Reset() {
	*x = AdminFormDescriptor{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormDescriptor) ProtoMessage() {}

func (x *AdminFormDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormDescriptor.ProtoReflect.Descriptor instead.
func (*AdminFormDescriptor) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *AdminFormDescriptor) GetFields() []*AdminFormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminFormDescriptor) GetSubmitLabel() string {
	if x != nil {
		return x.SubmitLabel
	}
	return ""
}

type ConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEntry) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type HttpRouteDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Access          string                 `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	Navigable       bool                   `protobuf:"varint,5,opt,name=navigable,proto3" json:"navigable,omitempty"`
	NavigationLabel string                 `protobuf:"bytes,6,opt,name=navigation_label,json=navigationLabel,proto3" json:"navigation_label,omitempty"`
	NavigationKind  string                 `protobuf:"bytes,7,opt,name=navigation_kind,json=navigationKind,proto3" json:"navigation_kind,omitempty"`
	StaticAsset     bool                   `protobuf:"varint,8,opt,name=static_asset,json=staticAsset,proto3" json:"static_asset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpRouteDescriptor) Reset() {
	*x = HttpRouteDescriptor{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteDescriptor) ProtoMessage() {}

func (x *HttpRouteDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteDescriptor.ProtoReflect.Descriptor instead.
func (*HttpRouteDescriptor) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *HttpRouteDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpRouteDescriptor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRouteDescriptor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRouteDescriptor) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *HttpRouteDescriptor) GetNavigable() bool {
	if x != nil {
		return x.Navigable
	}
	return false
}

func (x *HttpRouteDescriptor) GetNavigationLabel() string {
	if x != nil {
		return x.NavigationLabel
	}
	return ""
}

func (x *HttpRouteDescriptor) GetNavigationKind() string {
	if x != nil {
		return x.NavigationKind
	}
	return ""
}

func (x *HttpRouteDescriptor) GetStaticAsset() bool {
	if x != nil {
		return x.StaticAsset
	}
	return false
}

type PackagedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Integrity     string                 `protobuf:"bytes,3,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagedAsset) Reset() {
	*x = PackagedAsset{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagedAsset) ProtoMessage() {}

func (x *PackagedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagedAsset.ProtoReflect.Descriptor instead.
func (*PackagedAsset) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *PackagedAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PackagedAsset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PackagedAsset) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

type CapabilityDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Subscriptions []string               `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	ConfigSchema  []*ConfigSchema        `protobuf:"bytes,6,rep,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CapabilityDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CapabilityDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CapabilityDescriptor) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CapabilityDescriptor) GetConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *CapabilityDescriptor) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PluginManifest struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	PluginId            string                  `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version             string                  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum            string                  `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ContinuumApiVersion string                  `protobuf:"bytes,4,opt,name=continuum_api_version,json=continuumApiVersion,proto3" json:"continuum_api_version,omitempty"`
	SupportedPlatforms  []*SupportedPlatform    `protobuf:"bytes,5,rep,name=supported_platforms,json=supportedPlatforms,proto3" json:"supported_platforms,omitempty"`
	Capabilities        []*CapabilityDescriptor `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	GlobalConfigSchema  []*ConfigSchema         `protobuf:"bytes,7,rep,name=global_config_schema,json=globalConfigSchema,proto3" json:"global_config_schema,omitempty"`
	UserConfigSchema    []*ConfigSchema         `protobuf:"bytes,8,rep,name=user_config_schema,json=userConfigSchema,proto3" json:"user_config_schema,omitempty"`
	HttpRoutes          []*HttpRouteDescriptor  `protobuf:"bytes,9,rep,name=http_routes,json=httpRoutes,proto3" json:"http_routes,omitempty"`
	Assets              []*PackagedAsset        `protobuf:"bytes,10,rep,name=assets,proto3" json:"assets,omitempty"`
	Metadata            *structpb.Struct        `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *PluginManifest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PluginManifest) GetContinuumApiVersion() string {
	if x != nil {
		return x.ContinuumApiVersion
	}
	return ""
}

func (x *PluginManifest) GetSupportedPlatforms() []*SupportedPlatform {
	if x != nil {
		return x.SupportedPlatforms
	}
	return nil
}

func (x *PluginManifest) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginManifest) GetGlobalConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.GlobalConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetUserConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.UserConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetHttpRoutes() []*HttpRouteDescriptor {
	if x != nil {
		return x.HttpRoutes
	}
	return nil
}

func (x *PluginManifest) GetAssets() []*PackagedAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *PluginManifest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{10}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *PluginManifest        `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *GetManifestResponse) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*ConfigEntry         `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigureRequest) GetConfig() []*ConfigEntry {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{13}
}

var File_continuum_plugin_v1_common_proto protoreflect.FileDescriptor

const file_continuum_plugin_v1_common_proto_rawDesc = "" +
	"\n" +
	" continuum/plugin/v1/common.proto\x12\x13continuum.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"7\n" +
	"\x11SupportedPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"\xde\x01\n" +
	"\fConfigSchema\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vjson_schema\x18\x04 \x01(\tR\n" +
	"jsonSchema\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12G\n" +
	"\n" +
	"admin_form\x18\x06 \x01(\v2(.continuum.plugin.v1.AdminFormDescriptorR\tadminForm\"_\n" +
	"\x0fAdminFormOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa0\x03\n" +
	"\x0eAdminFormField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12?\n" +
	"\acontrol\x18\x04 \x01(\x0e2%.continuum.plugin.v1.AdminFormControlR\acontrol\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\a \x01(\bR\x06secret\x12\x1c\n" +
	"\tmultiline\x18\b \x01(\bR\tmultiline\x12;\n" +
	"\rdefault_value\x18\t \x01(\v2\x16.google.protobuf.ValueR\fdefaultValue\x12>\n" +
	"\aoptions\x18\n" +
	" \x03(\v2$.continuum.plugin.v1.AdminFormOptionR\aoptions\x12\x12\n" +
	"\x04rows\x18\v \x01(\x05R\x04rows\"u\n" +
	"\x13AdminFormDescriptor\x12;\n" +
	"\x06fields\x18\x01 \x03(\v2#.continuum.plugin.v1.AdminFormFieldR\x06fields\x12!\n" +
	"\fsubmit_label\x18\x02 \x01(\tR\vsubmitLabel\"N\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\"\xfe\x01\n" +
	"\x13HttpRouteDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06access\x18\x04 \x01(\tR\x06access\x12\x1c\n" +
	"\tnavigable\x18\x05 \x01(\bR\tnavigable\x12)\n" +
	"\x10navigation_label\x18\x06 \x01(\tR\x0fnavigationLabel\x12'\n" +
	"\x0fnavigation_kind\x18\a \x01(\tR\x0enavigationKind\x12!\n" +
	"\fstatic_asset\x18\b \x01(\bR\vstaticAsset\"d\n" +
	"\rPackagedAsset\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1c\n" +
	"\tintegrity\x18\x03 \x01(\tR\tintegrity\"\xa2\x02\n" +
	"\x14CapabilityDescriptor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\x12F\n" +
	"\rconfig_schema\x18\x06 \x03(\v2!.continuum.plugin.v1.ConfigSchemaR\fconfigSchema\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xa1\x05\n" +
	"\x0ePluginManifest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x122\n" +
	"\x15continuum_api_version\x18\x04 \x01(\tR\x13continuumApiVersion\x12W\n" +
	"\x13supported_platforms\x18\x05 \x03(\v2&.continuum.plugin.v1.SupportedPlatformR\x12supportedPlatforms\x12M\n" +
	"\fcapabilities\x18\x06 \x03(\v2).continuum.plugin.v1.CapabilityDescriptorR\fcapabilities\x12S\n" +
	"\x14global_config_schema\x18\a \x03(\v2!.continuum.plugin.v1.ConfigSchemaR\x12globalConfigSchema\x12O\n" +
	"\x12user_config_schema\x18\b \x03(\v2!.continuum.plugin.v1.ConfigSchemaR\x10userConfigSchema\x12I\n" +
	"\vhttp_routes\x18\t \x03(\v2(.continuum.plugin.v1.HttpRouteDescriptorR\n" +
	"httpRoutes\x12:\n" +
	"\x06assets\x18\n" +
	" \x03(\v2\".continuum.plugin.v1.PackagedAssetR\x06assets\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x14\n" +
	"\x12GetManifestRequest\"V\n" +
	"\x13GetManifestResponse\x12?\n" +
	"\bmanifest\x18\x01 \x01(\v2#.continuum.plugin.v1.PluginManifestR\bmanifest\"L\n" +
	"\x10ConfigureRequest\x128\n" +
	"\x06config\x18\x01 \x03(\v2 .continuum.plugin.v1.ConfigEntryR\x06config\"\x13\n" +
	"\x11ConfigureResponse*\xf2\x01\n" +
	"\x10AdminFormControl\x12\"\n" +
	"\x1eADMIN_FORM_CONTROL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ADMIN_FORM_CONTROL_TEXT\x10\x01\x12\x1f\n" +
	"\x1bADMIN_FORM_CONTROL_TEXTAREA\x10\x02\x12\x1f\n" +
	"\x1bADMIN_FORM_CONTROL_PASSWORD\x10\x03\x12\x1d\n" +
	"\x19ADMIN_FORM_CONTROL_NUMBER\x10\x04\x12\x1d\n" +
	"\x19ADMIN_FORM_CONTROL_SWITCH\x10\x05\x12\x1d\n" +
	"\x19ADMIN_FORM_CONTROL_SELECT\x10\x062\xc7\x01\n" +
	"\aRuntime\x12`\n" +
	"\vGetManifest\x12'.continuum.plugin.v1.GetManifestRequest\x1a(.continuum.plugin.v1.GetManifestResponse\x12Z\n" +
	"\tConfigure\x12%.continuum.plugin.v1.ConfigureRequest\x1a&.continuum.plugin.v1.ConfigureResponseB[ZYgithub.com/ContinuumApp/continuum-plugin-sdk/pkg/pluginproto/continuum/plugin/v1;pluginv1b\x06proto3"

var (
	file_continuum_plugin_v1_common_proto_rawDescOnce sync.Once
	file_continuum_plugin_v1_common_proto_rawDescData []byte
)

func file_continuum_plugin_v1_common_proto_rawDescGZIP() []byte {
	file_continuum_plugin_v1_common_proto_rawDescOnce.Do(func() {
		file_continuum_plugin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuum_plugin_v1_common_proto_rawDesc), len(file_continuum_plugin_v1_common_proto_rawDesc)))
	})
	return file_continuum_plugin_v1_common_proto_rawDescData
}

var file_continuum_plugin_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_continuum_plugin_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_continuum_plugin_v1_common_proto_goTypes = []any{
	(AdminFormControl)(0),        // 0: continuum.plugin.v1.AdminFormControl
	(*SupportedPlatform)(nil),    // 1: continuum.plugin.v1.SupportedPlatform
	(*ConfigSchema)(nil),         // 2: continuum.plugin.v1.ConfigSchema
	(*AdminFormOption)(nil),      // 3: continuum.plugin.v1.AdminFormOption
	(*AdminFormField)(nil),       // 4: continuum.plugin.v1.AdminFormField
	(*AdminFormDescriptor)(nil),  // 5: continuum.plugin.v1.AdminFormDescriptor
	(*ConfigEntry)(nil),          // 6: continuum.plugin.v1.ConfigEntry
	(*HttpRouteDescriptor)(nil),  // 7: continuum.plugin.v1.HttpRouteDescriptor
	(*PackagedAsset)(nil),        // 8: continuum.plugin.v1.PackagedAsset
	(*CapabilityDescriptor)(nil), // 9: continuum.plugin.v1.CapabilityDescriptor
	(*PluginManifest)(nil),       // 10: continuum.plugin.v1.PluginManifest
	(*GetManifestRequest)(nil),   // 11: continuum.plugin.v1.GetManifestRequest
	(*GetManifestResponse)(nil),  // 12: continuum.plugin.v1.GetManifestResponse
	(*ConfigureRequest)(nil),     // 13: continuum.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),    // 14: continuum.plugin.v1.ConfigureResponse
	(*structpb.Value)(nil),       // 15: google.protobuf.Value
	(*structpb.Struct)(nil),      // 16: google.protobuf.Struct
}
var file_continuum_plugin_v1_common_proto_depIdxs = []int32{
	5,  // 0: continuum.plugin.v1.ConfigSchema.admin_form:type_name -> continuum.plugin.v1.AdminFormDescriptor
	0,  // 1: continuum.plugin.v1.AdminFormField.control:type_name -> continuum.plugin.v1.AdminFormControl
	15, // 2: continuum.plugin.v1.AdminFormField.default_value:type_name -> google.protobuf.Value
	3,  // 3: continuum.plugin.v1.AdminFormField.options:type_name -> continuum.plugin.v1.AdminFormOption
	4,  // 4: continuum.plugin.v1.AdminFormDescriptor.fields:type_name -> continuum.plugin.v1.AdminFormField
	16, // 5: continuum.plugin.v1.ConfigEntry.value:type_name -> google.protobuf.Struct
	2,  // 6: continuum.plugin.v1.CapabilityDescriptor.config_schema:type_name -> continuum.plugin.v1.ConfigSchema
	16, // 7: continuum.plugin.v1.CapabilityDescriptor.metadata:type_name -> google.protobuf.Struct
	1,  // 8: continuum.plugin.v1.PluginManifest.supported_platforms:type_name -> continuum.plugin.v1.SupportedPlatform
	9,  // 9: continuum.plugin.v1.PluginManifest.capabilities:type_name -> continuum.plugin.v1.CapabilityDescriptor
	2,  // 10: continuum.plugin.v1.PluginManifest.global_config_schema:type_name -> continuum.plugin.v1.ConfigSchema
	2,  // 11: continuum.plugin.v1.PluginManifest.user_config_schema:type_name -> continuum.plugin.v1.ConfigSchema
	7,  // 12: continuum.plugin.v1.PluginManifest.http_routes:type_name -> continuum.plugin.v1.HttpRouteDescriptor
	8,  // 13: continuum.plugin.v1.PluginManifest.assets:type_name -> continuum.plugin.v1.PackagedAsset
	16, // 14: continuum.plugin.v1.PluginManifest.metadata:type_name -> google.protobuf.Struct
	10, // 15: continuum.plugin.v1.GetManifestResponse.manifest:type_name -> continuum.plugin.v1.PluginManifest
	6,  // 16: continuum.plugin.v1.ConfigureRequest.config:type_name -> continuum.plugin.v1.ConfigEntry
	11, // 17: continuum.plugin.v1.Runtime.GetManifest:input_type -> continuum.plugin.v1.GetManifestRequest
	13, // 18: continuum.plugin.v1.Runtime.Configure:input_type -> continuum.plugin.v1.ConfigureRequest
	12, // 19: continuum.plugin.v1.Runtime.GetManifest:output_type -> continuum.plugin.v1.GetManifestResponse
	14, // 20: continuum.plugin.v1.Runtime.Configure:output_type -> continuum.plugin.v1.ConfigureResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_continuum_plugin_v1_common_proto_init() }
func file_continuum_plugin_v1_common_proto_init() {
	if File_continuum_plugin_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuum_plugin_v1_common_proto_rawDesc), len(file_continuum_plugin_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_continuum_plugin_v1_common_proto_goTypes,
		DependencyIndexes: file_continuum_plugin_v1_common_proto_depIdxs,
		EnumInfos:         file_continuum_plugin_v1_common_proto_enumTypes,
		MessageInfos:      file_continuum_plugin_v1_common_proto_msgTypes,
	}.Build()
	File_continuum_plugin_v1_common_proto = out.File
	file_continuum_plugin_v1_common_proto_goTypes = nil
	file_continuum_plugin_v1_common_proto_depIdxs = nil
}
