// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: continuum/plugin/v1/common.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportedPlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedPlatform) Reset() {
	*x = SupportedPlatform{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedPlatform) ProtoMessage() {}

func (x *SupportedPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedPlatform.ProtoReflect.Descriptor instead.
func (*SupportedPlatform) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedPlatform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SupportedPlatform) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	JsonSchema    string                 `protobuf:"bytes,4,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSchema) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSchema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConfigSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *ConfigSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEntry) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type HttpRouteDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Access          string                 `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	Navigable       bool                   `protobuf:"varint,5,opt,name=navigable,proto3" json:"navigable,omitempty"`
	NavigationLabel string                 `protobuf:"bytes,6,opt,name=navigation_label,json=navigationLabel,proto3" json:"navigation_label,omitempty"`
	NavigationKind  string                 `protobuf:"bytes,7,opt,name=navigation_kind,json=navigationKind,proto3" json:"navigation_kind,omitempty"`
	StaticAsset     bool                   `protobuf:"varint,8,opt,name=static_asset,json=staticAsset,proto3" json:"static_asset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpRouteDescriptor) Reset() {
	*x = HttpRouteDescriptor{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteDescriptor) ProtoMessage() {}

func (x *HttpRouteDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteDescriptor.ProtoReflect.Descriptor instead.
func (*HttpRouteDescriptor) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *HttpRouteDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpRouteDescriptor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRouteDescriptor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRouteDescriptor) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *HttpRouteDescriptor) GetNavigable() bool {
	if x != nil {
		return x.Navigable
	}
	return false
}

func (x *HttpRouteDescriptor) GetNavigationLabel() string {
	if x != nil {
		return x.NavigationLabel
	}
	return ""
}

func (x *HttpRouteDescriptor) GetNavigationKind() string {
	if x != nil {
		return x.NavigationKind
	}
	return ""
}

func (x *HttpRouteDescriptor) GetStaticAsset() bool {
	if x != nil {
		return x.StaticAsset
	}
	return false
}

type PackagedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Integrity     string                 `protobuf:"bytes,3,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagedAsset) Reset() {
	*x = PackagedAsset{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagedAsset) ProtoMessage() {}

func (x *PackagedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagedAsset.ProtoReflect.Descriptor instead.
func (*PackagedAsset) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *PackagedAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PackagedAsset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PackagedAsset) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

type CapabilityDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Subscriptions []string               `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	ConfigSchema  []*ConfigSchema        `protobuf:"bytes,6,rep,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilityDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CapabilityDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CapabilityDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CapabilityDescriptor) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CapabilityDescriptor) GetConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *CapabilityDescriptor) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PluginManifest struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	PluginId            string                  `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version             string                  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum            string                  `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ContinuumApiVersion string                  `protobuf:"bytes,4,opt,name=continuum_api_version,json=continuumApiVersion,proto3" json:"continuum_api_version,omitempty"`
	SupportedPlatforms  []*SupportedPlatform    `protobuf:"bytes,5,rep,name=supported_platforms,json=supportedPlatforms,proto3" json:"supported_platforms,omitempty"`
	Capabilities        []*CapabilityDescriptor `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	GlobalConfigSchema  []*ConfigSchema         `protobuf:"bytes,7,rep,name=global_config_schema,json=globalConfigSchema,proto3" json:"global_config_schema,omitempty"`
	UserConfigSchema    []*ConfigSchema         `protobuf:"bytes,8,rep,name=user_config_schema,json=userConfigSchema,proto3" json:"user_config_schema,omitempty"`
	HttpRoutes          []*HttpRouteDescriptor  `protobuf:"bytes,9,rep,name=http_routes,json=httpRoutes,proto3" json:"http_routes,omitempty"`
	Assets              []*PackagedAsset        `protobuf:"bytes,10,rep,name=assets,proto3" json:"assets,omitempty"`
	Metadata            *structpb.Struct        `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *PluginManifest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PluginManifest) GetContinuumApiVersion() string {
	if x != nil {
		return x.ContinuumApiVersion
	}
	return ""
}

func (x *PluginManifest) GetSupportedPlatforms() []*SupportedPlatform {
	if x != nil {
		return x.SupportedPlatforms
	}
	return nil
}

func (x *PluginManifest) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginManifest) GetGlobalConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.GlobalConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetUserConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.UserConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetHttpRoutes() []*HttpRouteDescriptor {
	if x != nil {
		return x.HttpRoutes
	}
	return nil
}

func (x *PluginManifest) GetAssets() []*PackagedAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *PluginManifest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{7}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *PluginManifest        `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *GetManifestResponse) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*ConfigEntry         `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureRequest) GetConfig() []*ConfigEntry {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_continuum_plugin_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_continuum_plugin_v1_common_proto_rawDescGZIP(), []int{10}
}

var File_continuum_plugin_v1_common_proto protoreflect.FileDescriptor

const file_continuum_plugin_v1_common_proto_rawDesc = "" +
	"\n" +
	" continuum/plugin/v1/common.proto\x12\x13continuum.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"7\n" +
	"\x11SupportedPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"\x95\x01\n" +
	"\fConfigSchema\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vjson_schema\x18\x04 \x01(\tR\n" +
	"jsonSchema\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\"N\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\"\xfe\x01\n" +
	"\x13HttpRouteDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06access\x18\x04 \x01(\tR\x06access\x12\x1c\n" +
	"\tnavigable\x18\x05 \x01(\bR\tnavigable\x12)\n" +
	"\x10navigation_label\x18\x06 \x01(\tR\x0fnavigationLabel\x12'\n" +
	"\x0fnavigation_kind\x18\a \x01(\tR\x0enavigationKind\x12!\n" +
	"\fstatic_asset\x18\b \x01(\bR\vstaticAsset\"d\n" +
	"\rPackagedAsset\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1c\n" +
	"\tintegrity\x18\x03 \x01(\tR\tintegrity\"\xa2\x02\n" +
	"\x14CapabilityDescriptor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\x12F\n" +
	"\rconfig_schema\x18\x06 \x03(\v2!.continuum.plugin.v1.ConfigSchemaR\fconfigSchema\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xa1\x05\n" +
	"\x0ePluginManifest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x122\n" +
	"\x15continuum_api_version\x18\x04 \x01(\tR\x13continuumApiVersion\x12W\n" +
	"\x13supported_platforms\x18\x05 \x03(\v2&.continuum.plugin.v1.SupportedPlatformR\x12supportedPlatforms\x12M\n" +
	"\fcapabilities\x18\x06 \x03(\v2).continuum.plugin.v1.CapabilityDescriptorR\fcapabilities\x12S\n" +
	"\x14global_config_schema\x18\a \x03(\v2!.continuum.plugin.v1.ConfigSchemaR\x12globalConfigSchema\x12O\n" +
	"\x12user_config_schema\x18\b \x03(\v2!.continuum.plugin.v1.ConfigSchemaR\x10userConfigSchema\x12I\n" +
	"\vhttp_routes\x18\t \x03(\v2(.continuum.plugin.v1.HttpRouteDescriptorR\n" +
	"httpRoutes\x12:\n" +
	"\x06assets\x18\n" +
	" \x03(\v2\".continuum.plugin.v1.PackagedAssetR\x06assets\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x14\n" +
	"\x12GetManifestRequest\"V\n" +
	"\x13GetManifestResponse\x12?\n" +
	"\bmanifest\x18\x01 \x01(\v2#.continuum.plugin.v1.PluginManifestR\bmanifest\"L\n" +
	"\x10ConfigureRequest\x128\n" +
	"\x06config\x18\x01 \x03(\v2 .continuum.plugin.v1.ConfigEntryR\x06config\"\x13\n" +
	"\x11ConfigureResponse2\xc7\x01\n" +
	"\aRuntime\x12`\n" +
	"\vGetManifest\x12'.continuum.plugin.v1.GetManifestRequest\x1a(.continuum.plugin.v1.GetManifestResponse\x12Z\n" +
	"\tConfigure\x12%.continuum.plugin.v1.ConfigureRequest\x1a&.continuum.plugin.v1.ConfigureResponseB[ZYgithub.com/ContinuumApp/continuum-plugin-sdk/pkg/pluginproto/continuum/plugin/v1;pluginv1b\x06proto3"

var (
	file_continuum_plugin_v1_common_proto_rawDescOnce sync.Once
	file_continuum_plugin_v1_common_proto_rawDescData []byte
)

func file_continuum_plugin_v1_common_proto_rawDescGZIP() []byte {
	file_continuum_plugin_v1_common_proto_rawDescOnce.Do(func() {
		file_continuum_plugin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuum_plugin_v1_common_proto_rawDesc), len(file_continuum_plugin_v1_common_proto_rawDesc)))
	})
	return file_continuum_plugin_v1_common_proto_rawDescData
}

var file_continuum_plugin_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_continuum_plugin_v1_common_proto_goTypes = []any{
	(*SupportedPlatform)(nil),    // 0: continuum.plugin.v1.SupportedPlatform
	(*ConfigSchema)(nil),         // 1: continuum.plugin.v1.ConfigSchema
	(*ConfigEntry)(nil),          // 2: continuum.plugin.v1.ConfigEntry
	(*HttpRouteDescriptor)(nil),  // 3: continuum.plugin.v1.HttpRouteDescriptor
	(*PackagedAsset)(nil),        // 4: continuum.plugin.v1.PackagedAsset
	(*CapabilityDescriptor)(nil), // 5: continuum.plugin.v1.CapabilityDescriptor
	(*PluginManifest)(nil),       // 6: continuum.plugin.v1.PluginManifest
	(*GetManifestRequest)(nil),   // 7: continuum.plugin.v1.GetManifestRequest
	(*GetManifestResponse)(nil),  // 8: continuum.plugin.v1.GetManifestResponse
	(*ConfigureRequest)(nil),     // 9: continuum.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),    // 10: continuum.plugin.v1.ConfigureResponse
	(*structpb.Struct)(nil),      // 11: google.protobuf.Struct
}
var file_continuum_plugin_v1_common_proto_depIdxs = []int32{
	11, // 0: continuum.plugin.v1.ConfigEntry.value:type_name -> google.protobuf.Struct
	1,  // 1: continuum.plugin.v1.CapabilityDescriptor.config_schema:type_name -> continuum.plugin.v1.ConfigSchema
	11, // 2: continuum.plugin.v1.CapabilityDescriptor.metadata:type_name -> google.protobuf.Struct
	0,  // 3: continuum.plugin.v1.PluginManifest.supported_platforms:type_name -> continuum.plugin.v1.SupportedPlatform
	5,  // 4: continuum.plugin.v1.PluginManifest.capabilities:type_name -> continuum.plugin.v1.CapabilityDescriptor
	1,  // 5: continuum.plugin.v1.PluginManifest.global_config_schema:type_name -> continuum.plugin.v1.ConfigSchema
	1,  // 6: continuum.plugin.v1.PluginManifest.user_config_schema:type_name -> continuum.plugin.v1.ConfigSchema
	3,  // 7: continuum.plugin.v1.PluginManifest.http_routes:type_name -> continuum.plugin.v1.HttpRouteDescriptor
	4,  // 8: continuum.plugin.v1.PluginManifest.assets:type_name -> continuum.plugin.v1.PackagedAsset
	11, // 9: continuum.plugin.v1.PluginManifest.metadata:type_name -> google.protobuf.Struct
	6,  // 10: continuum.plugin.v1.GetManifestResponse.manifest:type_name -> continuum.plugin.v1.PluginManifest
	2,  // 11: continuum.plugin.v1.ConfigureRequest.config:type_name -> continuum.plugin.v1.ConfigEntry
	7,  // 12: continuum.plugin.v1.Runtime.GetManifest:input_type -> continuum.plugin.v1.GetManifestRequest
	9,  // 13: continuum.plugin.v1.Runtime.Configure:input_type -> continuum.plugin.v1.ConfigureRequest
	8,  // 14: continuum.plugin.v1.Runtime.GetManifest:output_type -> continuum.plugin.v1.GetManifestResponse
	10, // 15: continuum.plugin.v1.Runtime.Configure:output_type -> continuum.plugin.v1.ConfigureResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_continuum_plugin_v1_common_proto_init() }
func file_continuum_plugin_v1_common_proto_init() {
	if File_continuum_plugin_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuum_plugin_v1_common_proto_rawDesc), len(file_continuum_plugin_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_continuum_plugin_v1_common_proto_goTypes,
		DependencyIndexes: file_continuum_plugin_v1_common_proto_depIdxs,
		MessageInfos:      file_continuum_plugin_v1_common_proto_msgTypes,
	}.Build()
	File_continuum_plugin_v1_common_proto = out.File
	file_continuum_plugin_v1_common_proto_goTypes = nil
	file_continuum_plugin_v1_common_proto_depIdxs = nil
}
